services:
  - type: web
    name: telegram-hf-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false   # Telegram BotFather token
      - key: HF_SPACE_ID
        value: madarauchihagmailcom/My
      - key: HF_API_TOKEN
        sync: false   # only if the Space is private
